version: '3.9'
services:
  app:
    container_name: app
    build:
      context: lw2_service
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "3000:3000"
