version: '3'
services:
  app:
    image: node_app
          - .:/home/node/app
          - node_modules:/home/node/app/node_modules    
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - SERVER_PORT=$SERVER_PORT
      - SECRET_KEY=$SECRET_KEY
    container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
volumes:
  node_modules:
